language: node_js

node_js:
  - 16.2

notifications:
  email: false

addons:
  apt:
    packages:
    - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache

  override:
    - npm ci
    - npm run cy:verify

script:
  - npm run start:ci &
  - npm run cy:run -- --record
  - kill $(jobs -p) || true
  - cypress run --record --key c19ddfb4-7c7e-46bd-b124-68c394d8f1af